
version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  build:
    docker:
      - image: alpine:3.7
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: build
          command: |
            echo 'Hello World'
            echo 'My name is: ' $name
      - print_pipeline_id
workflows:
  my_workflow:
    jobs:
      - build
