version: 2.1

commands:
  sayhello:
    description: " A very simple command for demonstrating the purposes for commands"
    parameters:
      to:
        type: string
        default: "Hello world"
    steps:
      - run: echo << parameter.to >>

jobs:
  test:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - sayhello

workflows:
  default:
    jobs:
      - test
